# Shell variables
# Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/cowboy-blue.jpg"

# Special
background='#090404'
foreground='#c1c0c0'
cursor='#c1c0c0'

# Colors
color0='#090404'
color1='#394559'
color2='#565E6C'
color3='#B37A48'
color4='#737A85'
color5='#7C838C'
color6='#999CA3'
color7='#c1c0c0'
color8='#665353'
color9='#394559'
color10='#565E6C'
color11='#B37A48'
color12='#737A85'
color13='#7C838C'
color14='#999CA3'
color15='#c1c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
