export wallpaper="{{wallpaper}}"
export background="{{background}}"
export foreground="{{foreground}}"
export cursor="{{cursor}}"

export color0="{{color0}}"
export color1="{{color1}}"
export color2="{{color2}}"
export color3="{{color3}}"
export color4="{{color4}}"
export color5="{{color5}}"
export color6="{{color6}}"
export color7="{{color7}}"
export color8="{{color8}}"
export color9="{{color9}}"
export color10="{{color10}}"
export color11="{{color11}}"
export color12="{{color12}}"
export color13="{{color13}}"
export color14="{{color14}}"
export color15="{{color15}}"

export FZF_DEFAULT_OPTS="--color=fg:{{foreground}},bg:{{background}},hl:{{color4}},fg+:{{foreground}},bg+:{{color8}},hl+:{{color6}},info:{{color5}},prompt:{{color4}},pointer:{{color6}},marker:{{color2}},spinner:{{color4}},header:{{color4}}"
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
