backend = "full"
color_space = "lab"
palette = "dark16"
check_contrast = true

[templates]
waybar = { src = "colors-waybar.css", target = "~/.cache/wallust/colors-waybar.css" }
sway = { src = "colors-sway", target = "~/.cache/wallust/colors-sway" }
swaync = { src = "colors.css", target = "~/.cache/wallust/colors.css" }
kitty = { src = "colors-kitty.conf", target = "~/.cache/wallust/colors-kitty.conf" }
swaylock = { src = "swaylock-config", target = "~/.cache/wallust/swaylock-config" }
wofi = { src = "colors-waybar.css", target = "~/.cache/wallust/colors-wofi.css" }
shell = { src = "colors.sh", target = "~/.cache/wallust/colors.sh" }
wob = { src = "wob.ini", target = "~/.cache/wallust/wob.ini" }
tmux = { src = "colors-tmux.conf", target = "~/.cache/wallust/colors-tmux.conf" }
nvim = { src = "colors-wallust.lua", target = "~/.cache/wallust/colors-wallust.lua" }
